import Footer from '../components/Footer/Footer.jsx';
import Header from '../components/Header/Header.jsx';
import {api} from '../utils/Api.js';
import './vendor/normalize.scss';
import './vendor/global.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
async function getData() {
  const data = await api.getCities();
  const cities = data[0].areas;
  return cities;
}
async function findUniversities(params) {
  "use server"
  const data = await api.getUniversity(params);
  return data.items;
}
export default async function RootLayout({children}) {
  const cities = await getData();
  const univers = [];

  return (
    <html lang="ru">
      <body>
        <Header cities={cities} univers={univers} findUniversities={findUniversities}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
