import logo from './logoHeader.svg';
import arrow from './arrow.svg';
import UniversPhoto from './UniversPhoto.jpeg';
import logoUnivers from './logoUnivers.png';
import bell from './bell.svg';
import heart from './heart.svg';
import downold from './downold.svg';
import avatar from './avatar.svg';
import fon from './fon.jpg';
import cardPhoto from './Tech.jpg';
import icon__bank from './icon__bank.svg';
import icon__bed from './icon__bed.svg';
import icon__flag from './icon__bank.svg';
export {logo, arrow, UniversPhoto, logoUnivers, bell, heart, downold, avatar, fon,icon__bank,icon__bed,icon__flag,cardPhoto};
